### ISSUE TITLE
Source modifications for dropbearssh 

### ISSUE THREAD

**Issue by gattilorenz** [classilla/dclinux#1]
Could you upload the source modifications to dropbearssh to /usr/src, as you mentioned in the blog?

**Comment by classilla** [comment]
There are no source modifications. It was built directly from the current dropbear sources as of time of build. If you're having trouble building it, make sure you have NFS swap on; otherwise post the error you're seeing.

**Comment by gattilorenz** [comment]
I misunderstood the blog post, where it mentioned "minimal changes" - I was just curious to see _which_ changes it took to build on a vintage compiler
